/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as TeamRouteImport } from './routes/_team'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitationActionRouteImport } from './routes/invitation.$action'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthOtpRouteImport } from './routes/_auth/otp'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as TeamTeamIndexRouteImport } from './routes/_team/$team/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as TeamTeamTeamRouteImport } from './routes/_team/$team/team'
import { Route as TeamTeamSuccessRouteImport } from './routes/_team/$team/success'
import { Route as TeamTeamSettingsRouteImport } from './routes/_team/$team/settings'
import { Route as TeamTeamProfileRouteImport } from './routes/_team/$team/profile'
import { Route as TeamTeamPlansRouteImport } from './routes/_team/$team/plans'
import { Route as AuthResetPasswordVerifyRouteImport } from './routes/_auth/reset-password/verify'
import { Route as AuthEmailVerificationRouteImport } from './routes/_auth/email.verification'
import { Route as TeamTeamReferralListIndexRouteImport } from './routes/_team/$team/referral-list/index'
import { Route as TeamTeamMileageLogIndexRouteImport } from './routes/_team/$team/mileage-log/index'
import { Route as TeamTeamMasterListIndexRouteImport } from './routes/_team/$team/master-list/index'
import { Route as TeamTeamSettingsBillingRouteImport } from './routes/_team/$team/settings/billing'
import { Route as TeamTeamReferralListCountyConfigRouteImport } from './routes/_team/$team/referral-list/county-config'
import { Route as TeamTeamMasterListLeadsLeadIndexRouteImport } from './routes/_team/$team/master-list/leads/$lead/index'
import { Route as TeamTeamMasterListLeadsLeadTimelineRouteImport } from './routes/_team/$team/master-list/leads/$lead/timeline'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/_team',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationActionRoute = InvitationActionRouteImport.update({
  id: '/invitation/$action',
  path: '/invitation/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const TeamTeamIndexRoute = TeamTeamIndexRouteImport.update({
  id: '/$team/',
  path: '/$team/',
  getParentRoute: () => TeamRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRoute,
} as any)
const TeamTeamTeamRoute = TeamTeamTeamRouteImport.update({
  id: '/$team/team',
  path: '/$team/team',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamSuccessRoute = TeamTeamSuccessRouteImport.update({
  id: '/$team/success',
  path: '/$team/success',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamSettingsRoute = TeamTeamSettingsRouteImport.update({
  id: '/$team/settings',
  path: '/$team/settings',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamProfileRoute = TeamTeamProfileRouteImport.update({
  id: '/$team/profile',
  path: '/$team/profile',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamPlansRoute = TeamTeamPlansRouteImport.update({
  id: '/$team/plans',
  path: '/$team/plans',
  getParentRoute: () => TeamRoute,
} as any)
const AuthResetPasswordVerifyRoute = AuthResetPasswordVerifyRouteImport.update({
  id: '/reset-password/verify',
  path: '/reset-password/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/email/verification',
  path: '/email/verification',
  getParentRoute: () => AuthRoute,
} as any)
const TeamTeamReferralListIndexRoute =
  TeamTeamReferralListIndexRouteImport.update({
    id: '/$team/referral-list/',
    path: '/$team/referral-list/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMileageLogIndexRoute = TeamTeamMileageLogIndexRouteImport.update({
  id: '/$team/mileage-log/',
  path: '/$team/mileage-log/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamMasterListIndexRoute = TeamTeamMasterListIndexRouteImport.update({
  id: '/$team/master-list/',
  path: '/$team/master-list/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamSettingsBillingRoute = TeamTeamSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => TeamTeamSettingsRoute,
} as any)
const TeamTeamReferralListCountyConfigRoute =
  TeamTeamReferralListCountyConfigRouteImport.update({
    id: '/$team/referral-list/county-config',
    path: '/$team/referral-list/county-config',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMasterListLeadsLeadIndexRoute =
  TeamTeamMasterListLeadsLeadIndexRouteImport.update({
    id: '/$team/master-list/leads/$lead/',
    path: '/$team/master-list/leads/$lead/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMasterListLeadsLeadTimelineRoute =
  TeamTeamMasterListLeadsLeadTimelineRouteImport.update({
    id: '/$team/master-list/leads/$lead/timeline',
    path: '/$team/master-list/leads/$lead/timeline',
    getParentRoute: () => TeamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/register': typeof AuthRegisterRoute
  '/invitation/$action': typeof InvitationActionRoute
  '/email/verification': typeof AuthEmailVerificationRoute
  '/reset-password/verify': typeof AuthResetPasswordVerifyRoute
  '/$team/plans': typeof TeamTeamPlansRoute
  '/$team/profile': typeof TeamTeamProfileRoute
  '/$team/settings': typeof TeamTeamSettingsRouteWithChildren
  '/$team/success': typeof TeamTeamSuccessRoute
  '/$team/team': typeof TeamTeamTeamRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/$team': typeof TeamTeamIndexRoute
  '/$team/referral-list/county-config': typeof TeamTeamReferralListCountyConfigRoute
  '/$team/settings/billing': typeof TeamTeamSettingsBillingRoute
  '/$team/master-list': typeof TeamTeamMasterListIndexRoute
  '/$team/mileage-log': typeof TeamTeamMileageLogIndexRoute
  '/$team/referral-list': typeof TeamTeamReferralListIndexRoute
  '/$team/master-list/leads/$lead/timeline': typeof TeamTeamMasterListLeadsLeadTimelineRoute
  '/$team/master-list/leads/$lead': typeof TeamTeamMasterListLeadsLeadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/register': typeof AuthRegisterRoute
  '/invitation/$action': typeof InvitationActionRoute
  '/email/verification': typeof AuthEmailVerificationRoute
  '/reset-password/verify': typeof AuthResetPasswordVerifyRoute
  '/$team/plans': typeof TeamTeamPlansRoute
  '/$team/profile': typeof TeamTeamProfileRoute
  '/$team/settings': typeof TeamTeamSettingsRouteWithChildren
  '/$team/success': typeof TeamTeamSuccessRoute
  '/$team/team': typeof TeamTeamTeamRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/$team': typeof TeamTeamIndexRoute
  '/$team/referral-list/county-config': typeof TeamTeamReferralListCountyConfigRoute
  '/$team/settings/billing': typeof TeamTeamSettingsBillingRoute
  '/$team/master-list': typeof TeamTeamMasterListIndexRoute
  '/$team/mileage-log': typeof TeamTeamMileageLogIndexRoute
  '/$team/referral-list': typeof TeamTeamReferralListIndexRoute
  '/$team/master-list/leads/$lead/timeline': typeof TeamTeamMasterListLeadsLeadTimelineRoute
  '/$team/master-list/leads/$lead': typeof TeamTeamMasterListLeadsLeadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_team': typeof TeamRouteWithChildren
  '/billing': typeof BillingRoute
  '/onboarding': typeof OnboardingRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/otp': typeof AuthOtpRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/invitation/$action': typeof InvitationActionRoute
  '/_auth/email/verification': typeof AuthEmailVerificationRoute
  '/_auth/reset-password/verify': typeof AuthResetPasswordVerifyRoute
  '/_team/$team/plans': typeof TeamTeamPlansRoute
  '/_team/$team/profile': typeof TeamTeamProfileRoute
  '/_team/$team/settings': typeof TeamTeamSettingsRouteWithChildren
  '/_team/$team/success': typeof TeamTeamSuccessRoute
  '/_team/$team/team': typeof TeamTeamTeamRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_team/$team/': typeof TeamTeamIndexRoute
  '/_team/$team/referral-list/county-config': typeof TeamTeamReferralListCountyConfigRoute
  '/_team/$team/settings/billing': typeof TeamTeamSettingsBillingRoute
  '/_team/$team/master-list/': typeof TeamTeamMasterListIndexRoute
  '/_team/$team/mileage-log/': typeof TeamTeamMileageLogIndexRoute
  '/_team/$team/referral-list/': typeof TeamTeamReferralListIndexRoute
  '/_team/$team/master-list/leads/$lead/timeline': typeof TeamTeamMasterListLeadsLeadTimelineRoute
  '/_team/$team/master-list/leads/$lead/': typeof TeamTeamMasterListLeadsLeadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/onboarding'
    | '/login'
    | '/otp'
    | '/register'
    | '/invitation/$action'
    | '/email/verification'
    | '/reset-password/verify'
    | '/$team/plans'
    | '/$team/profile'
    | '/$team/settings'
    | '/$team/success'
    | '/$team/team'
    | '/reset-password'
    | '/$team'
    | '/$team/referral-list/county-config'
    | '/$team/settings/billing'
    | '/$team/master-list'
    | '/$team/mileage-log'
    | '/$team/referral-list'
    | '/$team/master-list/leads/$lead/timeline'
    | '/$team/master-list/leads/$lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/onboarding'
    | '/login'
    | '/otp'
    | '/register'
    | '/invitation/$action'
    | '/email/verification'
    | '/reset-password/verify'
    | '/$team/plans'
    | '/$team/profile'
    | '/$team/settings'
    | '/$team/success'
    | '/$team/team'
    | '/reset-password'
    | '/$team'
    | '/$team/referral-list/county-config'
    | '/$team/settings/billing'
    | '/$team/master-list'
    | '/$team/mileage-log'
    | '/$team/referral-list'
    | '/$team/master-list/leads/$lead/timeline'
    | '/$team/master-list/leads/$lead'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_team'
    | '/billing'
    | '/onboarding'
    | '/_auth/login'
    | '/_auth/otp'
    | '/_auth/register'
    | '/invitation/$action'
    | '/_auth/email/verification'
    | '/_auth/reset-password/verify'
    | '/_team/$team/plans'
    | '/_team/$team/profile'
    | '/_team/$team/settings'
    | '/_team/$team/success'
    | '/_team/$team/team'
    | '/_auth/reset-password/'
    | '/_team/$team/'
    | '/_team/$team/referral-list/county-config'
    | '/_team/$team/settings/billing'
    | '/_team/$team/master-list/'
    | '/_team/$team/mileage-log/'
    | '/_team/$team/referral-list/'
    | '/_team/$team/master-list/leads/$lead/timeline'
    | '/_team/$team/master-list/leads/$lead/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  TeamRoute: typeof TeamRouteWithChildren
  BillingRoute: typeof BillingRoute
  OnboardingRoute: typeof OnboardingRoute
  InvitationActionRoute: typeof InvitationActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_team': {
      id: '/_team'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$action': {
      id: '/invitation/$action'
      path: '/invitation/$action'
      fullPath: '/invitation/$action'
      preLoaderRoute: typeof InvitationActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/otp': {
      id: '/_auth/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_team/$team/': {
      id: '/_team/$team/'
      path: '/$team'
      fullPath: '/$team'
      preLoaderRoute: typeof TeamTeamIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_team/$team/team': {
      id: '/_team/$team/team'
      path: '/$team/team'
      fullPath: '/$team/team'
      preLoaderRoute: typeof TeamTeamTeamRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/success': {
      id: '/_team/$team/success'
      path: '/$team/success'
      fullPath: '/$team/success'
      preLoaderRoute: typeof TeamTeamSuccessRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/settings': {
      id: '/_team/$team/settings'
      path: '/$team/settings'
      fullPath: '/$team/settings'
      preLoaderRoute: typeof TeamTeamSettingsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/profile': {
      id: '/_team/$team/profile'
      path: '/$team/profile'
      fullPath: '/$team/profile'
      preLoaderRoute: typeof TeamTeamProfileRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/plans': {
      id: '/_team/$team/plans'
      path: '/$team/plans'
      fullPath: '/$team/plans'
      preLoaderRoute: typeof TeamTeamPlansRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_auth/reset-password/verify': {
      id: '/_auth/reset-password/verify'
      path: '/reset-password/verify'
      fullPath: '/reset-password/verify'
      preLoaderRoute: typeof AuthResetPasswordVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/email/verification': {
      id: '/_auth/email/verification'
      path: '/email/verification'
      fullPath: '/email/verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_team/$team/referral-list/': {
      id: '/_team/$team/referral-list/'
      path: '/$team/referral-list'
      fullPath: '/$team/referral-list'
      preLoaderRoute: typeof TeamTeamReferralListIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/mileage-log/': {
      id: '/_team/$team/mileage-log/'
      path: '/$team/mileage-log'
      fullPath: '/$team/mileage-log'
      preLoaderRoute: typeof TeamTeamMileageLogIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/': {
      id: '/_team/$team/master-list/'
      path: '/$team/master-list'
      fullPath: '/$team/master-list'
      preLoaderRoute: typeof TeamTeamMasterListIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/settings/billing': {
      id: '/_team/$team/settings/billing'
      path: '/billing'
      fullPath: '/$team/settings/billing'
      preLoaderRoute: typeof TeamTeamSettingsBillingRouteImport
      parentRoute: typeof TeamTeamSettingsRoute
    }
    '/_team/$team/referral-list/county-config': {
      id: '/_team/$team/referral-list/county-config'
      path: '/$team/referral-list/county-config'
      fullPath: '/$team/referral-list/county-config'
      preLoaderRoute: typeof TeamTeamReferralListCountyConfigRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/leads/$lead/': {
      id: '/_team/$team/master-list/leads/$lead/'
      path: '/$team/master-list/leads/$lead'
      fullPath: '/$team/master-list/leads/$lead'
      preLoaderRoute: typeof TeamTeamMasterListLeadsLeadIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/leads/$lead/timeline': {
      id: '/_team/$team/master-list/leads/$lead/timeline'
      path: '/$team/master-list/leads/$lead/timeline'
      fullPath: '/$team/master-list/leads/$lead/timeline'
      preLoaderRoute: typeof TeamTeamMasterListLeadsLeadTimelineRouteImport
      parentRoute: typeof TeamRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthResetPasswordVerifyRoute: typeof AuthResetPasswordVerifyRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthResetPasswordVerifyRoute: AuthResetPasswordVerifyRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface TeamTeamSettingsRouteChildren {
  TeamTeamSettingsBillingRoute: typeof TeamTeamSettingsBillingRoute
}

const TeamTeamSettingsRouteChildren: TeamTeamSettingsRouteChildren = {
  TeamTeamSettingsBillingRoute: TeamTeamSettingsBillingRoute,
}

const TeamTeamSettingsRouteWithChildren =
  TeamTeamSettingsRoute._addFileChildren(TeamTeamSettingsRouteChildren)

interface TeamRouteChildren {
  TeamTeamPlansRoute: typeof TeamTeamPlansRoute
  TeamTeamProfileRoute: typeof TeamTeamProfileRoute
  TeamTeamSettingsRoute: typeof TeamTeamSettingsRouteWithChildren
  TeamTeamSuccessRoute: typeof TeamTeamSuccessRoute
  TeamTeamTeamRoute: typeof TeamTeamTeamRoute
  TeamTeamIndexRoute: typeof TeamTeamIndexRoute
  TeamTeamReferralListCountyConfigRoute: typeof TeamTeamReferralListCountyConfigRoute
  TeamTeamMasterListIndexRoute: typeof TeamTeamMasterListIndexRoute
  TeamTeamMileageLogIndexRoute: typeof TeamTeamMileageLogIndexRoute
  TeamTeamReferralListIndexRoute: typeof TeamTeamReferralListIndexRoute
  TeamTeamMasterListLeadsLeadTimelineRoute: typeof TeamTeamMasterListLeadsLeadTimelineRoute
  TeamTeamMasterListLeadsLeadIndexRoute: typeof TeamTeamMasterListLeadsLeadIndexRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamTeamPlansRoute: TeamTeamPlansRoute,
  TeamTeamProfileRoute: TeamTeamProfileRoute,
  TeamTeamSettingsRoute: TeamTeamSettingsRouteWithChildren,
  TeamTeamSuccessRoute: TeamTeamSuccessRoute,
  TeamTeamTeamRoute: TeamTeamTeamRoute,
  TeamTeamIndexRoute: TeamTeamIndexRoute,
  TeamTeamReferralListCountyConfigRoute: TeamTeamReferralListCountyConfigRoute,
  TeamTeamMasterListIndexRoute: TeamTeamMasterListIndexRoute,
  TeamTeamMileageLogIndexRoute: TeamTeamMileageLogIndexRoute,
  TeamTeamReferralListIndexRoute: TeamTeamReferralListIndexRoute,
  TeamTeamMasterListLeadsLeadTimelineRoute:
    TeamTeamMasterListLeadsLeadTimelineRoute,
  TeamTeamMasterListLeadsLeadIndexRoute: TeamTeamMasterListLeadsLeadIndexRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  TeamRoute: TeamRouteWithChildren,
  BillingRoute: BillingRoute,
  OnboardingRoute: OnboardingRoute,
  InvitationActionRoute: InvitationActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
