/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TeamRouteImport } from './routes/_team'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as TeamTeamIndexRouteImport } from './routes/_team/$team/index'
import { Route as TeamTeamTeamRouteImport } from './routes/_team/$team/team'
import { Route as TeamTeamMasterListIndexRouteImport } from './routes/_team/$team/master-list/index'
import { Route as TeamTeamMasterListLeadsLeadIndexRouteImport } from './routes/_team/$team/master-list/leads/$lead/index'
import { Route as TeamTeamMasterListLeadsLeadTimelineRouteImport } from './routes/_team/$team/master-list/leads/$lead/timeline'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/_team',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const TeamTeamIndexRoute = TeamTeamIndexRouteImport.update({
  id: '/$team/',
  path: '/$team/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamTeamRoute = TeamTeamTeamRouteImport.update({
  id: '/$team/team',
  path: '/$team/team',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamMasterListIndexRoute = TeamTeamMasterListIndexRouteImport.update({
  id: '/$team/master-list/',
  path: '/$team/master-list/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamMasterListLeadsLeadIndexRoute =
  TeamTeamMasterListLeadsLeadIndexRouteImport.update({
    id: '/$team/master-list/leads/$lead/',
    path: '/$team/master-list/leads/$lead/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMasterListLeadsLeadTimelineRoute =
  TeamTeamMasterListLeadsLeadTimelineRouteImport.update({
    id: '/$team/master-list/leads/$lead/timeline',
    path: '/$team/master-list/leads/$lead/timeline',
    getParentRoute: () => TeamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/onboarding': typeof OnboardingRoute
  '/register': typeof AuthRegisterRoute
  '/': typeof AuthIndexRoute
  '/$team/team': typeof TeamTeamTeamRoute
  '/$team': typeof TeamTeamIndexRoute
  '/$team/master-list': typeof TeamTeamMasterListIndexRoute
  '/$team/master-list/leads/$lead/timeline': typeof TeamTeamMasterListLeadsLeadTimelineRoute
  '/$team/master-list/leads/$lead': typeof TeamTeamMasterListLeadsLeadIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/register': typeof AuthRegisterRoute
  '/': typeof AuthIndexRoute
  '/$team/team': typeof TeamTeamTeamRoute
  '/$team': typeof TeamTeamIndexRoute
  '/$team/master-list': typeof TeamTeamMasterListIndexRoute
  '/$team/master-list/leads/$lead/timeline': typeof TeamTeamMasterListLeadsLeadTimelineRoute
  '/$team/master-list/leads/$lead': typeof TeamTeamMasterListLeadsLeadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_team': typeof TeamRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/': typeof AuthIndexRoute
  '/_team/$team/team': typeof TeamTeamTeamRoute
  '/_team/$team/': typeof TeamTeamIndexRoute
  '/_team/$team/master-list/': typeof TeamTeamMasterListIndexRoute
  '/_team/$team/master-list/leads/$lead/timeline': typeof TeamTeamMasterListLeadsLeadTimelineRoute
  '/_team/$team/master-list/leads/$lead/': typeof TeamTeamMasterListLeadsLeadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/onboarding'
    | '/register'
    | '/'
    | '/$team/team'
    | '/$team'
    | '/$team/master-list'
    | '/$team/master-list/leads/$lead/timeline'
    | '/$team/master-list/leads/$lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/register'
    | '/'
    | '/$team/team'
    | '/$team'
    | '/$team/master-list'
    | '/$team/master-list/leads/$lead/timeline'
    | '/$team/master-list/leads/$lead'
  id:
    | '__root__'
    | '/_auth'
    | '/_team'
    | '/onboarding'
    | '/_auth/register'
    | '/_auth/'
    | '/_team/$team/team'
    | '/_team/$team/'
    | '/_team/$team/master-list/'
    | '/_team/$team/master-list/leads/$lead/timeline'
    | '/_team/$team/master-list/leads/$lead/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  TeamRoute: typeof TeamRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_team': {
      id: '/_team'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_team/$team/': {
      id: '/_team/$team/'
      path: '/$team'
      fullPath: '/$team'
      preLoaderRoute: typeof TeamTeamIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/team': {
      id: '/_team/$team/team'
      path: '/$team/team'
      fullPath: '/$team/team'
      preLoaderRoute: typeof TeamTeamTeamRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/': {
      id: '/_team/$team/master-list/'
      path: '/$team/master-list'
      fullPath: '/$team/master-list'
      preLoaderRoute: typeof TeamTeamMasterListIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/leads/$lead/': {
      id: '/_team/$team/master-list/leads/$lead/'
      path: '/$team/master-list/leads/$lead'
      fullPath: '/$team/master-list/leads/$lead'
      preLoaderRoute: typeof TeamTeamMasterListLeadsLeadIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/leads/$lead/timeline': {
      id: '/_team/$team/master-list/leads/$lead/timeline'
      path: '/$team/master-list/leads/$lead/timeline'
      fullPath: '/$team/master-list/leads/$lead/timeline'
      preLoaderRoute: typeof TeamTeamMasterListLeadsLeadTimelineRouteImport
      parentRoute: typeof TeamRoute
    }
  }
}

interface AuthRouteChildren {
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface TeamRouteChildren {
  TeamTeamTeamRoute: typeof TeamTeamTeamRoute
  TeamTeamIndexRoute: typeof TeamTeamIndexRoute
  TeamTeamMasterListIndexRoute: typeof TeamTeamMasterListIndexRoute
  TeamTeamMasterListLeadsLeadTimelineRoute: typeof TeamTeamMasterListLeadsLeadTimelineRoute
  TeamTeamMasterListLeadsLeadIndexRoute: typeof TeamTeamMasterListLeadsLeadIndexRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamTeamTeamRoute: TeamTeamTeamRoute,
  TeamTeamIndexRoute: TeamTeamIndexRoute,
  TeamTeamMasterListIndexRoute: TeamTeamMasterListIndexRoute,
  TeamTeamMasterListLeadsLeadTimelineRoute:
    TeamTeamMasterListLeadsLeadTimelineRoute,
  TeamTeamMasterListLeadsLeadIndexRoute: TeamTeamMasterListLeadsLeadIndexRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  TeamRoute: TeamRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
